"""
Volatility-timing strategy for R_25 (Volatility 25 Index), 10-tick Higher/Lower.

This replaces the earlier EMA9/EMA21 + momentum candle strategy. Backtesting
(384 pullback-pattern combinations, a 5-feature logistic regression, a
6-signal conviction ensemble, autocorrelation/variance-ratio/runs tests, and
an RNG periodicity check) found NO exploitable directional signal on this
instrument -- consistent with Deriv's own description of synthetic indices as
generated by a cryptographically secure RNG. Direction is therefore fixed
(config.bet_direction), not computed.

What *is* real: tick-return magnitude clusters in time (autocorrelation of
|return| ~0.013 at lags 1-50 for R_25) even though direction doesn't. This
strategy trades that -- it fires only when trailing realized volatility is in
the top `vol_target_percentile` of its own recent history, which raises the
probability that a 10-tick move clears the barrier in *either* direction. It
does not, and cannot, predict which direction.

Honest bottom line (see config.py's PnL note for the full figures): this gets
closer to breakeven than anything else tested, but the validated win rate
(31.9-32.0%) is still below the breakeven implied by the quoted payout
(33.33%). This is provided as the closest validated configuration found, not
as a claim of profitability.
"""

from collections import deque
from dataclasses import dataclass
from typing import Optional
import math


@dataclass
class SignalDecision:
    direction: str          # "HIGHER" or "LOWER" -- always config.bet_direction
    current_vol: float       # rolling realized volatility at the moment of firing
    threshold: float         # the trailing-percentile threshold it cleared
    percentile: float        # the configured target percentile (for display/logging)
    reason: str


class RollingVolatility:
    """O(1)-amortized rolling standard deviation of tick-to-tick price changes
    over the last `window` ticks. Uses only ticks seen so far (no lookahead),
    matching backtest/adaptive_strategy.py's rolling_std."""

    def __init__(self, window: int):
        if window <= 1:
            raise ValueError("window must be > 1")
        self.window = window
        self._prices: deque[float] = deque(maxlen=window + 1)
        self._sum = 0.0
        self._sumsq = 0.0
        self._deltas: deque[float] = deque(maxlen=window)

    def update(self, price: float) -> Optional[float]:
        """Feed one new tick price. Returns the current rolling std of tick
        deltas, or None until the window has filled."""
        self._prices.append(price)
        if len(self._prices) < 2:
            return None
        delta = self._prices[-1] - self._prices[-2]
        if len(self._deltas) == self.window:
            old = self._deltas[0]
            self._sum -= old
            self._sumsq -= old * old
        self._deltas.append(delta)
        self._sum += delta
        self._sumsq += delta * delta
        if len(self._deltas) < self.window:
            return None
        n = len(self._deltas)
        mean = self._sum / n
        variance = max(self._sumsq / n - mean * mean, 0.0)
        return math.sqrt(variance)


class VolatilityTimingStrategy:
    """Stateless decision function: given the current rolling volatility
    reading and the current trailing-percentile threshold (both computed
    elsewhere -- see engine.py's VolatilityTracker, which owns the actual
    rolling window and the persisted trailing-day history), decide whether a
    signal qualifies. Kept separate from state-tracking so this part stays
    trivially unit-testable, matching the original design intent of this file.
    """

    def __init__(self, bet_direction: str, target_percentile: float):
        direction = bet_direction.upper().strip()
        if direction not in {"HIGHER", "LOWER"}:
            raise ValueError(f"bet_direction must be HIGHER or LOWER, got {bet_direction!r}")
        self.bet_direction = direction
        self.target_percentile = target_percentile

    def evaluate(self, current_vol: Optional[float], threshold: Optional[float]) -> Optional[SignalDecision]:
        if current_vol is None or threshold is None:
            return None
        if current_vol < threshold:
            return None
        return SignalDecision(
            direction=self.bet_direction,
            current_vol=current_vol,
            threshold=threshold,
            percentile=self.target_percentile,
            reason=(
                f"volatility timing: rolling vol {current_vol:.5f} >= "
                f"trailing {self.target_percentile:.0f}th percentile threshold {threshold:.5f}"
            ),
        )
